# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: salamwaddah
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: claims
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Claims

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"
